trigger:
- none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: BuildJob
    displayName: Build Job

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Hello World"