parameters:
    world: ''

jobs:
  - job: A
    displayName: First Job
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Hello $(world)"
          
  - job: B
    displayName: Second Job
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Hello ${{ parameters.world }}"