trigger:
  - lab02
  
variables:
    world: the whole world
  
steps:
- task: PowerShell@2
  displayName: Using in YAML Var
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host "Hello $(world)"
      
- task: PowerShell@2
  displayName: Using Pipeline Var
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello $(great)"